// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASI6iVQXyLtSfFuSUkUhR3dUKK6EeMc8A',
    appId: '1:967525747730:web:396fd37add9af95a801ccb',
    messagingSenderId: '967525747730',
    projectId: 'emprende-uidemovil',
    authDomain: 'emprende-uidemovil.firebaseapp.com',
    storageBucket: 'emprende-uidemovil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-pbsTojokdq_6CfWbVTB3aZS_yfozRw',
    appId: '1:967525747730:android:1f69401c46a53b24801ccb',
    messagingSenderId: '967525747730',
    projectId: 'emprende-uidemovil',
    storageBucket: 'emprende-uidemovil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHrUeI-aFpsjJH6LQnvWo1mM-Iu-b-ZyU',
    appId: '1:967525747730:ios:d6fc9d725cd840f0801ccb',
    messagingSenderId: '967525747730',
    projectId: 'emprende-uidemovil',
    storageBucket: 'emprende-uidemovil.firebasestorage.app',
    iosBundleId: 'com.example.emprendeuidemovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHrUeI-aFpsjJH6LQnvWo1mM-Iu-b-ZyU',
    appId: '1:967525747730:ios:d6fc9d725cd840f0801ccb',
    messagingSenderId: '967525747730',
    projectId: 'emprende-uidemovil',
    storageBucket: 'emprende-uidemovil.firebasestorage.app',
    iosBundleId: 'com.example.emprendeuidemovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASI6iVQXyLtSfFuSUkUhR3dUKK6EeMc8A',
    appId: '1:967525747730:web:8d5e49b377368a60801ccb',
    messagingSenderId: '967525747730',
    projectId: 'emprende-uidemovil',
    authDomain: 'emprende-uidemovil.firebaseapp.com',
    storageBucket: 'emprende-uidemovil.firebasestorage.app',
  );
}
